name: rnd_market

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Node.js 18.19
      uses: actions/setup-node@v3
      with:
        node-version: 18.19

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/rnd_market_backend

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Create SSH directory
      run: mkdir -p ~/rnd_market/ssh

    - name: Install SSH key
      run: echo "${{ secrets.SSH_KEY }}" > ~/rnd_market/ssh/id_rsa && chmod 600 ~/rnd_market/ssh/id_rsa

    - name: Copy SSH key to known_hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/rnd_market/ssh/known_hosts

    - name: SSH into the Droplet, pull Docker image, and restart container
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/rnd_market/ssh/id_rsa ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/rnd_market_backend
          docker stop rnd_market_backend || true
          docker rm rnd_market_backend || true
          docker run -d --name rnd_market_backend -p 8002:3000 ${{ secrets.DOCKERHUB_USERNAME }}/rnd_market_backend
        EOF
